name:                tola-backend-api
version:             0.1.0.0
github:              "homam/tola-backend-api"
license:             BSD3
author:              "Homam"
maintainer:          "example@example.com"
copyright:           "2018 Homam"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/homam/tola-backend-api#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- cryptohash
- AES
- base16-bytestring
- base64-bytestring
- case-insensitive
- mtl
- transformers
- containers
- unordered-containers
- aeson
- http-conduit
- hspec
- hspec-wai
- hspec-expectations
- time
- wai
- wai-extra
- warp
- vault
- blaze-builder
- data-default-class 
- wai-logger
- ansi-terminal
- fast-logger
- lifted-base
- transformers-base
- scotty
- exceptions
- http-types
- resource-pool
- persistent
- persistent-template
- persistent-postgresql
- monad-logger
- monad-control
- http-client

library:
  source-dirs: src

executables:
  tola-backend-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tola-backend-api

tests:
  tola-backend-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tola-backend-api
